---
- name: update apt-keys
  command: apt-key update

- name: install deps
  become: yes
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - iftop
  tags:
    - screenrc

- name: create .screenrc from template
  template:
    src: screenrc.j2
    dest: ~/.screenrc
  tags:
    - screenrc